hash-format = "sha256"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "e241b319addd76573d10f56db272297d055e13958a5b977d20e3d6d5eb922b01"
metafile = true

[[files]]
file = "mods/auto-gg.pw.toml"
hash = "da17b555c53ce390b30cd6eb5357720fd2cca482fb5a927695ab8e74d679d3ad"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
hash = "ed6f8461bcc70d112a862f661a97ad2238f2c7fdc74ffa6efa79c6903abcc9b3"
metafile = true

[[files]]
file = "mods/bettercommandblockui.pw.toml"
hash = "89b555932f4f50e0f878ef589123d49d48552b182292102a7a569d2f3b3772a1"
metafile = true

[[files]]
file = "mods/betternightvision.pw.toml"
hash = "a80e53a334ee3bd4c2ac4f06cf156a7843c91953e3724d7b0a64484010c68c1d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "37892a1101fb31f445c6c9e913e5090fc7dc4d7949f6856effbeafd62ef80d01"
metafile = true

[[files]]
file = "mods/commandkeys.pw.toml"
hash = "7c6bed6fe415c1be9e5aabe39fe2753ae8c5aadf3098477decd1bb58cee2f936"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "d7e862814b817f85b06c1644d73464398c3d9bfdb4826991adad24226cb11840"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "811a955cdfbcdde0fe02363e9097a5ea20de4bb8f128aa6a7bdc651b4c9024bb"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "e918132ab17f31eacc1a055d54bba6ee59a208a5f43af7a89730b39698968ec7"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "71779fc9899faeb98a9a86440e6fd19bd766f5df246ea3d1c95edd1db7e52be1"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "344ca02ae26f79bc11dc6d65751503613964da6761fcda5a33291dc7d8aae36f"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "e1419604ca0254a69e9e5bb4ed6f8833b5f431d7e05f2e68b7729163114783de"
metafile = true

[[files]]
file = "mods/in-game-account-switcher.pw.toml"
hash = "fdbebbb20b67b8195b5b04d275224b07d050f9690e78573c653f238b892f559b"
metafile = true

[[files]]
file = "mods/island-utils.pw.toml"
hash = "942ef97ef2e13bc97e0ecfc02100b12a1d0798362b29398f5abe66ee77212a77"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "20a0aa411adf8f9ca018ec87e091911ea7dc22bdf882a9be62e19c52eb688077"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "7a50a38e40b8d9ab694892816d2550f17d0f8bb3c8fc3a13f9bded75369f91b3"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "f2c1c695efd87f14d6e20ad1632802ba5c50fc7e0c23cd7f7073f2ff6ffb130e"
metafile = true

[[files]]
file = "mods/noxesium.pw.toml"
hash = "c3008ffa0dcfa7a3ff7054a70d0081e88ed0d6393ef32d55581be4995598299b"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "75923b6cc33f6caa6d5189dd47f93633a6ef8e2cfc3b12794e53760639bd5883"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "e70b3bd1b5e68c5e4d9d1b3826b522dafca0fe604539ca08eef3283eb2f9f2bc"
metafile = true

[[files]]
file = "mods/simple-block-overlay.pw.toml"
hash = "50c3fd85dee4b904027359c75677a0a470337c13a961fd22ef0387edbeab8573"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "90df45c557b9bd0e6fb4af71d2970a0848635fba3cc73dcd95c8617d31a89b8f"
metafile = true

[[files]]
file = "mods/sound-controller.pw.toml"
hash = "b3c6f5c1b08426de2fb0815b9cc0f945236e7d81e05121e1c065110054cf3f21"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "1e0937b3389a835daef7ef08856a0a297d829142aeef4e9698a29d52efa0b602"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "f2908d9033570d993a21f671304f08edb7696d65260b58e2b55d0c943f9b172c"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "fa0cbf2db5b1010c41d64f04e2b2aaa079880bc58971ba621d0cbbc394cf85f7"
metafile = true

[[files]]
file = "mods/toggle-toggle-sprint.pw.toml"
hash = "ba7c986d1fdd9b3be52fb117f160aca629a05feb132e1bccbb7c5bc0c4775929"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f58d19dbd7d1ffe8d4b38f29d4ac0bd84a2c3b32ddb1cfe4eabab5eb02ee5d9f"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "c1c04a60b546354f69ebc6ae5f9168ff7d6fb3c12d53a92acbd63e234ea12293"
metafile = true
