name = "OneClient 1.21.1 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.1-fabric"
update-url = "oneclient/generated/utility-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5bf13b159e1cb188a47d0d87dc9af0fa6d7fe39a95bba5cb11b49827bdeaea9"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
