name = "OneClient 1.21.1 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.1-fabric"
update-url = "oneclient/generated/utility-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d81b8e0f3405605466a929e0202e53c97cb9ee18d560e90bb386c47ff09269d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
