hash-format = "sha256"

[[files]]
file = "mods/asyncparticles.pw.toml"
hash = "6ffe6afb16df9eb8c65fcb426f3402964012fc815d931fd3fcdb4f4f4e431cd9"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "bceef1ff8d0e144d32ea31964e38f52f422c56919f219f27c413b9da496a78de"
metafile = true

[[files]]
file = "mods/better-mipmaps.pw.toml"
hash = "f9d286c3ba8a9309820f9742fd6d278ae7586a1ec6ea5efad6d5146ae2b9268c"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "d2e365178207751d415f830d2e9d75c3b0ba1558bcaa6c1a079c0f732ba4bfaa"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "37892a1101fb31f445c6c9e913e5090fc7dc4d7949f6856effbeafd62ef80d01"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "e1cae1ebd7f98f7680a21b21ebbba142bc030cf1d733fe94e6516a9fa368a4cb"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "f96234c62f4e3fd26a4875bf6032fd2173eab797138b5cbf0b7dbfb4771e2e23"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0c11639e9841ab4134686bc1cd17a2d8040df58bd571969057fa578d07256f60"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "0e3e06b97216269caf1f4c153d222f5e39b38b64b8e88fee4c1b76b5648fc260"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "9f7822a4ddcc9548fb046aac89bd08e5a96d139ccdbf4ecce5ed3ac9e4558458"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "344ca02ae26f79bc11dc6d65751503613964da6761fcda5a33291dc7d8aae36f"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "d6044f19e23d380f2ad52ba69ae61c62a949b560fc9326dada59592f741b40e6"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "c37f4c3c2e3b6a15572b9550a985602667c2b5b1b1a3d613a3a15861a196bebb"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "4cff74bd476d0f2d9cfeb5176c2c0fbf5510d6a11de8343d077d28a25bfadc8d"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "a6be0d290ca6903988d05df68e1548f6cf21f8203608ab7c2bddad00f558e2ee"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
hash = "6f2b19011d3fac0ea1add0dbd0e96191b9792784ca9f8e9a2c1091af809dbbcf"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "9d651ef36c8ba89357d823b027f9a8375372c8f75f74012fefa09c5bc391117c"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "7823647c5cc50d11dea5c909fb7c12cfa1b0db4e47812155a2f9d8f026bb08c4"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "6e0fe347e010b9219e325e64ffb6e6b4c0046f030c952b0fee210636e79fa88f"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
hash = "cb0ea1b7957e7bfbc66fe88027f2fddf89d35bb2e1e9216d4acdaeaa87151930"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "c29b93f9fd26d79915d995695bcc51eb16bf5c0a6d8d3eb91cd057f73b86726b"
metafile = true

[[files]]
file = "mods/lazy-language-loader.pw.toml"
hash = "847a65082cab446494b66dd6fa0a960e21f6e125873400e8f9b61f3c1d948325"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0b2172e499c9f6932095ef19efebea67f575dad9d1122a0b0c5ed9f3c32b547e"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "88f6e64310c73b666086f4e764c8a6b184bc305a93846f7d36ffe5f366bca6a7"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "7a50a38e40b8d9ab694892816d2550f17d0f8bb3c8fc3a13f9bded75369f91b3"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "089a7a5af53243a3a4487c67d9b95575d11dd7eeeeb6dfb5b08e77c90228f1e0"
metafile = true

[[files]]
file = "mods/noxesium.pw.toml"
hash = "c719a89e1da00ef81a3d104d00357d45b1a28e44643a59ca153625cd31d45069"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "9bd4f9b6008be54bf3cddd4ea69765fbe59449c199f6784a02ba4d5192030b23"
metafile = true

[[files]]
file = "mods/quick-pack.pw.toml"
hash = "de7c2d6f66a0a11ffbce10a7c745ca26f13703d2668feb695851835ef3368543"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "1ce131865a03138d8a4ff2c038fff23b356d8639a77aae96142fdfa96fba67be"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "5a3883bb2d6b943edc61f1dff826a328f5acfa119b6ae1200c016eb95aa6839b"
metafile = true

[[files]]
file = "mods/sciophobia.pw.toml"
hash = "bb8ffdc5df8517e167251dc31599027b25a45462e3753b2123e73d3ffefd0337"
metafile = true

[[files]]
file = "mods/screenshot-compression.pw.toml"
hash = "907aee18759c4d065e85be37faf022610c7418768aaa5112c67a2b7d95353810"
metafile = true

[[files]]
file = "mods/serverpingerfixer.pw.toml"
hash = "dce1b022c9baf13e0ce2d8d4767b0b1f558d87582fbd96a8e1867f394b926890"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "22e703cbf93f358eb1d7f19ed8a83d4966575777c71c2ac58c2af0fd8ef5c2a5"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "14d71ea2aedbcc46b2c3afbf65ef7cfb9ed29355833ce64305b7743f90971ec8"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f58d19dbd7d1ffe8d4b38f29d4ac0bd84a2c3b32ddb1cfe4eabab5eb02ee5d9f"
metafile = true
