name = "OneClient 1.21.1 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.1-fabric"
update-url = "oneclient/generated/performance-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fc05d2d6fce991dfbf0fc6e906f87c71400592e09ad86be97b2b39df95a303b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
