name = "OneClient 1.21.1 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.1-fabric"
update-url = "oneclient/generated/performance-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fe0f699b7f309073e4100729d4ee7b9bf100ef8eb5bb2b2beb726dbbb3b4ed4"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
