name = "OneClient 1.21.8 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.21.8-fabric"
update-url = "oneclient/generated/pvp-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d323963504ea56c59fc3c8cbc332f6b9c817b724470f23b0a045ffc29df6bbde"

[versions]
fabric = "0.18.4"
minecraft = "1.21.8"
