name = "OneClient 1.21.11 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.21.11-fabric"
update-url = "oneclient/generated/skyblock-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a28bdeaf439d8d78a5ba0f2e01dc423837dc960ea248535d328d2530566b897"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
