name = "OneClient 1.21.11 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.21.11-fabric"
update-url = "oneclient/generated/skyblock-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c98be3aa75f08c2f134e04373353c01d6edd0a31eb1e53a9fca3c470481d125"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
