name = "OneClient 1.21.11 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.21.11-fabric"
update-url = "oneclient/generated/skyblock-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3635c3109d24e9a1e0fcd8f94f8f503b3ef54b61b963ed28ca1481671877bca8"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
