hash-format = "sha256"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "1e8673ac87db89b84cb1bb8712cb403899f2dc3d9ec69c84167966350c6400ad"
metafile = true

[[files]]
file = "mods/better-block-entities.pw.toml"
hash = "2424c07c041756f9bc611882e380c33dae2675015fe372ff4c5f2730022b3e70"
metafile = true

[[files]]
file = "mods/better-mipmaps.pw.toml"
hash = "4273e3044a11a77ab840a8652d24f591bf0aa71c4103de8b4993754a1a7242ab"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "b887586f6fce74f592e597c2c580187ea7f2a7f32b02a4247926845e69019dd7"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "bbf28818ac59c19583f03d516a86b508e7da7a591c28d071c4e53effd4865bf6"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "9dab92b89f7c0b7c214fff21bc48b86bc57d0990a15ded2f57a3d04647ea818a"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "152911aa0d3ec93dac17f12f9155162c50e2cfdb45438869243f10fe5fa8513a"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "67994d917a5dd72327b96bbde214e3ae0b324c045dca253797f9544aa8f6a005"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "5cda675d6e3c1b3e6da70d4b629c3082e672c4a78d1073fb043277d4c8b92e70"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "e7ad6ee627e419198198bb4a9883e8f7f8b78f17a26d148a2d8652731b9efab3"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "686b17ab6f71a606297734d205b083531b1ce8240a5be8015af4949fff03633c"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "4019d5492e1db485e4bdc248515ac390fd4edff201d5907e3bb88f1d878caf1e"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "38e946fdf6b9c1860f457cbc49598a81bd73da269e62a1b58ede79b8ebb7859e"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "e0a5061283c7084745ec0594b235ff33b1fd199af023a2dd6ba56f5d2fd26ee9"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
hash = "7b6dfdd7155a7e46370555c8dcc3f413bdd94c632f7926933ac5bbb63830f1da"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "1b7e33939272407738d8908c25a1a5943fab36b4c31ddde865d8cc79d1f9334d"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "c1f35d1e755fbe482cb68029a97fc8b3418805803a9aa5fece97ffcddd7e0d2f"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "bddcda25e9bac94d2f12bc60daf2767aca2ff2ad5f7270d82277155ddc4e205b"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
hash = "21e81416d9e8bc206bd933eb7ae2004fd7a6ecf6739dbb1766fad6b9b296b9d8"
metafile = true

[[files]]
file = "mods/lazy-language-loader.pw.toml"
hash = "39abe310e4efd71360d1273c021ea6e33fdc39a4d48e34d8a39989cc03bb9d66"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "eb426a809a5ed885d617e497092c35a467d7744a637e47f3b3f6e9b794c933ed"
metafile = true

[[files]]
file = "mods/log-cleaner.pw.toml"
hash = "ee38b691291acc163d76aa0b602c82af0f1bac571ed189bcbb81cd7fb4ea19be"
metafile = true

[[files]]
file = "mods/modernfix-mvus.pw.toml"
hash = "e422aafb44db20ba48628cb4809ce83b8b871eeead41226c222b278610f2261a"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "f4504187b6b7bea442fe8afd03818657ba5f28757e80afbaa2fbf160540f689b"
metafile = true

[[files]]
file = "mods/noxesium.pw.toml"
hash = "3d22391d697b39f61a5844e236a8e911d5404e076d457438972d77335d63f665"
metafile = true

[[files]]
file = "mods/optipainting-updated.pw.toml"
hash = "1136c6e06f915a55649e3fbcb681fd869238c5e82d25f97cbf3fb315e6d442b6"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "c2f0a76886e9409e348eddadc9ca134b87ec4c692dfdf5965c61cb5bea142370"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "cba4003d52d83dbe2166ae9a0693d7e74e8b31ead3dae69ab4def1aa2a195db5"
metafile = true

[[files]]
file = "mods/sciophobia.pw.toml"
hash = "366b85d8ae1f6cf52f6e999ba80f18a5428e23bc18db7f3b482a6d3481633b50"
metafile = true

[[files]]
file = "mods/serverpingerfixer.pw.toml"
hash = "5a113012ddf7470cc7897d5828a6dc398a6b17f4464169274f606a6d6390fb4a"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "31746f28560ea2421ca3837a517132a264f943a4e4500c74a731551f9aa3b6bf"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "08992629888934b4af4a4e478e69fb877d9bcf5f10511a33c32ddb03343d41f1"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "1765c84b093eba73f278a6f7af45f722445f35f08f8f9c103e6df42c28446f8e"
metafile = true
