name = "OneClient 1.21.11 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.11-fabric"
update-url = "oneclient/generated/performance-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1a837dd73201b60730eb3ac8afaa160d4bf9f43790e3d31c7ae4f727f2f840f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
