name = "OneClient 1.21.11 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.11-fabric"
update-url = "oneclient/generated/performance-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc2470a09e88ec2b2d6d823797212e09fa085966d277649fd3b2c90d435f9215"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
