name = "OneClient 1.21.8 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "HUD"
id = "hud-1.21.8-fabric"
update-url = "oneclient/generated/hud-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea78e3ac46540398116b494726d78411fe753bc909d02ab736d5294c3994a4ea"

[versions]
fabric = "0.18.4"
minecraft = "1.21.8"
