hash-format = "sha256"

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "71057ffacb79edc48ef50b33ba506255e3da4ad48e8d0eaa4635368097567ba9"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "344ca02ae26f79bc11dc6d65751503613964da6761fcda5a33291dc7d8aae36f"
metafile = true

[[files]]
file = "mods/firmament.pw.toml"
hash = "e8a0d012c303fad97a4fd77b115acb82e037a054fb445c5b38e90877892634f0"
metafile = true

[[files]]
file = "mods/hsm.pw.toml"
hash = "459a5515e9246e361e61d8b3b6fb2ffda11cdd34077270fe728599dbc589631d"
metafile = true

[[files]]
file = "mods/hypixel-mod-api.pw.toml"
hash = "23fb78f56ab631dcb4f249b64feb03293f1f44e39ea65b3eba7dcd37d74be005"
metafile = true

[[files]]
file = "mods/modern-warp-menu.pw.toml"
hash = "042142d252e8edaf9560e7b88a73619cdd47792fa04694ee99444196436345f1"
metafile = true

[[files]]
file = "mods/skyblock-custom-scoreboard.pw.toml"
hash = "c0a2bfdb1a74ed437d24b41041c16f45563129842ed16c084021d93e95aa8c49"
metafile = true

[[files]]
file = "mods/skyblock-profile-viewer.pw.toml"
hash = "c0be3dcc6b295f11dc0d6d9deb1bd929df9b461f2bc80c5e53aa911e97ce85ab"
metafile = true

[[files]]
file = "mods/skyblock-rpc.pw.toml"
hash = "95f16dd4275e96ed7db62db4083b0cadbf7a5b9644725b57a2edbcd488be9312"
metafile = true

[[files]]
file = "mods/skyblocker-liap.pw.toml"
hash = "fb4cb4fd85b81adca50dafd1a86a70da86b7041bce1075c493549381d1881485"
metafile = true

[[files]]
file = "mods/skycofl.pw.toml"
hash = "823521413b9047841ac097529e8774b93b40843c0e362ced9b8db474f97df4e6"
metafile = true

[[files]]
file = "mods/skycubed.pw.toml"
hash = "7450a136a8bc1c81b0a00cfabc1ececd2dfb27c3f9c56471973611dc2521ce07"
metafile = true

[[files]]
file = "mods/skyhanni.pw.toml"
hash = "52545c38e1a011bddfa035e995eae9905cde53cba1f6e91cf3a81a7b02191189"
metafile = true

[[files]]
file = "mods/skyocean.pw.toml"
hash = "f4029a18560d259d44825be5c696584d71cc7848ae76471c676a80f1da7da511"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "e3208008761017ce98dabe50c37fad65f56ece476d6b678b7d1eb9eab39bc1a1"
metafile = true
