name = "OneClient 1.21.10 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.21.10-fabric"
update-url = "oneclient/generated/skyblock-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcba25dead6eef44be579ab7c1c845c6d8bcb2e09154e34e35285ecc7f3fec33"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
