name = "OneClient 1.21.10 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.21.10-fabric"
update-url = "oneclient/generated/skyblock-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "785ec654bb5796f013daa93c20ba19263a5b84b83b496b6b14b8e6094f0e1fe6"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
