name = "OneClient 1.21.10 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.21.10-fabric"
update-url = "oneclient/generated/skyblock-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f12de34240146ea3259ae77642d36ba85415cee7ee08b94c32a9da3589c31b7d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
