name = "OneClient 1.21.8 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.21.8-fabric"
update-url = "oneclient/generated/skyblock-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12b899313ecb7199b5c5c2dd903f1689294a1bc7f1c886f19e39dc904d325aca"

[versions]
fabric = "0.18.4"
minecraft = "1.21.8"
