hash-format = "sha256"

[[files]]
file = "animatium_utility.json"
hash = "013bb87a1d68fdba744417b9591ed98e5e4c21c131868525967bca5e3a152c37"

[[files]]
file = "config/animatium.json"
hash = "d89b7ae345905cbad1bea445648c6812de635e69ce6d74d76b3ee9a5e0ebc683"

[[files]]
file = "config/customscoreboard/config.jsonc"
hash = "7bef58b3bb4952056ca1690c82a072b3cc1acc23a9b309bfe607abc525947dd0"

[[files]]
file = "config/one-click-join"
hash = "824b9b328245c5e74d87380a1e41c2a20f206b20f3144cd5551c4fabcfd0a55c"

[[files]]
file = "config/skyhanni/config.json"
hash = "0e9ea478eac394baa8ba87fa528bdcd9e13f2d0cbde05514793a34b523e2c252"

[[files]]
file = "data/fabricDefaultResourcePacks.dat"
hash = "8a952cb0935360d703ffcaf9d86fa018b1fcf37f286e76b4698145fed8cf309f"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "7695172e9df86f5133b995be57039fb2d46be7236acce5d64dc5d82e8238b9e3"
metafile = true

[[files]]
file = "mods/better-block-entities.pw.toml"
hash = "cbf5f18479ad424f759ea1fed5a108d5726beb060d11b8adcc262ba4a0fe4054"
metafile = true

[[files]]
file = "mods/better-mipmaps.pw.toml"
hash = "4917a2f0b5c000599c6ab52f6cf97e0145a9cbc88a4a0509d3758b6953952dd9"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "5aa82fb0c06d91065f89ca901f1982f0a17b2d6343084e8dc72643b08897e782"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "9c22bad4f0d606f92ce105da00204c29aa2b356401cc5d1088f63bb02f90d351"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "3881a6601432ff8a64f606f2acce55eef9e24f278be3af53ab17cf68b6d5d821"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "1016e9a0e9e72d5855556a02d968f08f9b0eb6b01e32625c7b585df639eda7da"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "ea9eb9fcc256ee0bd5863c3fe59bdaf4ef12abfe1d3b10684912bd093ce29b3f"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "639c1c25347f6b7fbc52d8dd718f787f1ff31925a1599277f7d614b295367d93"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "18a24b4aacdaeecf5ca8f582ab0c1d29d8ffde386b5d2eaad96ba30e936bfa26"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "344ca02ae26f79bc11dc6d65751503613964da6761fcda5a33291dc7d8aae36f"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "c092b37170a06ec6b3e3f39d89f8395d84a4abda3108c105f8687e8f51e3f2d1"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "4365ec402dd067112480eacf78b399d8701b5ad1e9d8de935058b42a335fa6d9"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "26d6a3dd41f9285ed4c49101a4d82ceb3d661105bc80e8fe901c71d8eab08538"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "a6be0d290ca6903988d05df68e1548f6cf21f8203608ab7c2bddad00f558e2ee"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
hash = "c4938e802660d7ecf2c5edb700f612b4456501bcb42bf7fd378cb6a86c99515a"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "290cda5439f0026546d987626f1b42e30814d8f7fc5951b3687cabcbd3dc92b1"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "39277bdb15567e9c94f584bb78e9cdd79372ad8f515e803ce1a208062559cd77"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "846b920ef6b5f3791d5ac83b094a98500b5475f6454f03c0fed5a797611bb2b5"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
hash = "c775399f55b3ad3b4f5ff8c1086282e6ddcf0208734a98de97efb2c1a848f9e3"
metafile = true

[[files]]
file = "mods/lazy-language-loader.pw.toml"
hash = "d283bbdc7382d5ea7a90c084dcbc20f2d5db6dc6c9fc31718e9a8bb7204af828"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "76a0d57502a209e66170fa7010af9a47210d2142879b7b0ca58050760b5106d2"
metafile = true

[[files]]
file = "mods/log-cleaner.pw.toml"
hash = "6a11f24debd05247a8df11859d78ace5c775fd82e8b8ae27b1ce3a8bc73234b1"
metafile = true

[[files]]
file = "mods/modernfix-mvus.pw.toml"
hash = "499c5e6cd3e6e7e7bcdb8ab4031353bebe883686e10a7d5f2ec4f2e4d05cd6e5"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "94828f99c4d81ae74fdc9daa04a45bb1bdc030d89140f265c323e9f9d03f2d9e"
metafile = true

[[files]]
file = "mods/noxesium.pw.toml"
hash = "c5e31342c5da4fa8fb4f004144b7b30d6de530f7aa83ccfbfea5035bcadb0d1c"
metafile = true

[[files]]
file = "mods/optipainting-updated.pw.toml"
hash = "cac130f0cdb7221ee6f4d64edf0b98fbd96313f9b179d7f74a15bc0ccd80c7f1"
metafile = true

[[files]]
file = "mods/quick-pack.pw.toml"
hash = "de7c2d6f66a0a11ffbce10a7c745ca26f13703d2668feb695851835ef3368543"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "10dceff617203714620c7f0e83a83d1e878c605f37dc982793210afe1149164a"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "a6cc9de613fdc2b276b9316526241ffe40d86787d2cc0d73c298c66d2e667b7c"
metafile = true

[[files]]
file = "mods/sciophobia.pw.toml"
hash = "c597d6945e6f508a01092197c2756866ad5707e031060f166884a914dc4f96b7"
metafile = true

[[files]]
file = "mods/screenshot-compression.pw.toml"
hash = "90519e5630fba8a081d2d433b22355234347453a9d75a0ed54ba25e313a20634"
metafile = true

[[files]]
file = "mods/serverpingerfixer.pw.toml"
hash = "dce1b022c9baf13e0ce2d8d4767b0b1f558d87582fbd96a8e1867f394b926890"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "e25de41e84aa6c910f89e78a7ee6098256e70d93793387910fd2f40b7b96cf71"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "d7fd524467ca69c3dfe9c6070d10987e99cc2c75756dd345948b377dc15f25bc"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "e3208008761017ce98dabe50c37fad65f56ece476d6b678b7d1eb9eab39bc1a1"
metafile = true

[[files]]
file = "options.txt"
hash = "dc12eba654f431846231f1d0874948e366650b5c8fe159b22b03c7f51646cbfa"

[[files]]
file = "servers.dat"
hash = "25e4bb9dbb4a7f0438311c03598d5c42c9256ae5e9c39af532f39712cd05b2c1"
