name = "OneClient 1.21.10 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.10-fabric"
update-url = "oneclient/generated/performance-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55b72dfd09a8e5e05f84d987056770415f769feb0206d6fa5188b63933d97cad"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
