name = "OneClient 1.21.11 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.11-fabric"
update-url = "oneclient/generated/utility-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb0655fbe2bcdde7564e91f299b250f3485e8bb271ee85bbd3ce51785fc95d75"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
