name = "OneClient 1.21.11 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "Utility"
id = "utility-1.21.11-fabric"
update-url = "oneclient/generated/utility-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fa3cebd289e6eedf3f29d4d6c91e46cae6ecd8175ff2b7742fa69904126e2fc"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
