hash-format = "sha256"

[[files]]
file = "mods/effecttimerplus.pw.toml"
hash = "a2cbb080f831364298bdf4d71c229d824f138209c24f32aaab0c568188c343f7"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "ca2147ccc6cd2a9d8ee484dd796ae8e1c5de42551c9366f2d09915bbe1c0002e"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "0f56ddc3a39115afee2da77ff35d9bff1e65a8aa757306f22db43be8d35e5b30"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "f4504187b6b7bea442fe8afd03818657ba5f28757e80afbaa2fbf160540f689b"
metafile = true

[[files]]
file = "mods/no-ones-view-model.pw.toml"
hash = "b403f0ebc6dd00ad51ffab1cc31c7eb9151188a165b0a56c30801adfe4c39d1e"
metafile = true

[[files]]
file = "mods/shaketweaks.pw.toml"
hash = "3c6f4cfa83fe6f71af4a208f93de2b19e503a34bbba35cb0f4cba499ca669793"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
hash = "6803f950a328127292642614dc2f01a35252fa1d889e8c1998d272934e82d31d"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "1765c84b093eba73f278a6f7af45f722445f35f08f8f9c103e6df42c28446f8e"
metafile = true
