name = "OneClient 1.21.11 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.21.11-fabric"
update-url = "oneclient/generated/pvp-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6158be1955738a7877fceefc63a42ff9fdbb83999c7bf8bfa175c7f48bc20f6a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
