hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "7410e83cb87d3c23ea24f38fdbbe1e3454c31ab87aba33dc607d26c5fc259870"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "7cbf5c3ddb93eac4f2ecbb04b07610ed4b80370f4f99d6d91ee1f1792528857d"
metafile = true

[[files]]
file = "mods/amecs.pw.toml"
hash = "19a5a44f59e4381bb916a7e8c43773f37580137350dcc62528ab24fefce416ed"
metafile = true

[[files]]
file = "mods/better-elytra-render.pw.toml"
hash = "e78ca1d1e1312a9b34ea3fe48adf3cdc58c3d504d77516d2c5c94c6aaaff1e25"
metafile = true

[[files]]
file = "mods/better-screens.pw.toml"
hash = "40b7b9e17abe33a7d9ca6cec7a9d3fce204838e5cedaabc8ab6bff197a47149a"
metafile = true

[[files]]
file = "mods/better-selection.pw.toml"
hash = "51e05f70450310a8f893f2b44f99103bcb26a5bb9323fded221039b2eb925c62"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "9604d6dbd95676622327340fc934337eecbae95f83e54a18caf9dbdb8962becd"
metafile = true

[[files]]
file = "mods/centered-crosshair.pw.toml"
hash = "ba4bf3fa860fb72b491ca8970703e37318aa5c6bd0a248f7af2a7ba3490c7fac"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "38f9517d9508846814b869adaf909846c95066e77ed381124abd3e661e7ce687"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "bbf28818ac59c19583f03d516a86b508e7da7a591c28d071c4e53effd4865bf6"
metafile = true

[[files]]
file = "mods/confirm-disconnect.pw.toml"
hash = "f970823279d7227eb25daeee04822777c0abd4f0965ff2bffa2357fad9fe7ab9"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "215f81b9480417e7e55fc70c6091129bfcd8e46da57cfc702603882e9a566cdc"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "e2ea9fbb81fb80bb8a65f398e95af99c7e6fcc060a1da5a8328d0adad702b6bc"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
hash = "85280cb9abd58da37c668c36f792fa2cd14ba3c31a85d56e4f42b2ebb2e75c74"
metafile = true

[[files]]
file = "mods/crosshairtweaks.pw.toml"
hash = "c77a49bba93124df0b663746cafb356a4fe1f4f38fe7735351e051c84e837787"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "2114081f8c55f654dad9015d85347ed440c7f0ff3f115f64b94e850337d2d920"
metafile = true

[[files]]
file = "mods/dark-graph.pw.toml"
hash = "6ea17d2471dd8d24c80d7f9abdee62f0d1969918c47805eb9d8889f378a96674"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "9497572a97551e67125f1546425f9b5d4373a9e1791b079f9029ed9b74255678"
metafile = true

[[files]]
file = "mods/droppeditemtweaks.pw.toml"
hash = "d82c06725d89ecf75df207e346b9da22dd4887ac4eb8b30f5871243b624d1f1d"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "60722287e7a1f3b7ca9aba9893ecf0db65822cf0af055bb44d423a79508c09ad"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "a2db8dfeb2eafb1cb8bbd08bd2d23a7c58c6bd8b6d5b9bfac759edc342c460e0"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "5698aab00158fb0ca7721c8b5201879a21a0657220652fedae19a7fa4d86bcca"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "0ce6d26133880efb7bd698347eb220c27e564ce244fa26a143dd4bbcae4201f5"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "ca2147ccc6cd2a9d8ee484dd796ae8e1c5de42551c9366f2d09915bbe1c0002e"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "e7ad6ee627e419198198bb4a9883e8f7f8b78f17a26d148a2d8652731b9efab3"
metafile = true

[[files]]
file = "mods/firmament-packet-fix.pw.toml"
hash = "d838aeda758f77f153c653702f6853567ffe7fa521201d577ed1d5144efb9d31"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "c4b2f70f7f520a4854522e5e028265832fe2759c9dba3dba9c7eeb185fb8cbc6"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "99c250d5c3812b19b8114340d51cb5af63d92b5dec954be73b3c729dcf5cf3c9"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "0f56ddc3a39115afee2da77ff35d9bff1e65a8aa757306f22db43be8d35e5b30"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "85d7f3c9e861c3b9b69175fed4ee02ed4620e87576b5bafa299e1493817ee393"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "d20bd490a12af7b26ff882c841ebd3bebbf6b413e14cfd4caea34910eb3eb928"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "f4504187b6b7bea442fe8afd03818657ba5f28757e80afbaa2fbf160540f689b"
metafile = true

[[files]]
file = "mods/mountopacity.pw.toml"
hash = "72d9ef180b0625a5c1cc59a855e5e3b6df8d8a4f4ed9008f26d7d7cacbb9756c"
metafile = true

[[files]]
file = "mods/nametagtweaks.pw.toml"
hash = "5e2c539c0c2098c3916891ab895ad0315d7e50b27d12c1866427233615d50d88"
metafile = true

[[files]]
file = "mods/nbt-autocomplete.pw.toml"
hash = "2ef9ab9aaf64752acc6b3e75d7f5127896d38bd837651cf3479f8ed28ee2f2ce"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "c44b4b553fec482a711b65bfc692c4d83ebe616cddd53d70ea1a9d976380104b"
metafile = true

[[files]]
file = "mods/notsoessential.pw.toml"
hash = "59764a2d66e56607ac143d1853017eeeb067508fc4063480699e085f8940417e"
metafile = true

[[files]]
file = "mods/numerical-enchantments.pw.toml"
hash = "053622e92d3627f18402606730dcafebfad7f78e2ff04feacb333f1c35738a42"
metafile = true

[[files]]
file = "mods/one-click-join.pw.toml"
hash = "234faf4ffa8c83b98106e440206bb079234c90149bea6297999c87bcac259cd5"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "2e16d8d581acfbf2a6be080859d906ca6c1358296149dad2be8565e3a23ddbfd"
metafile = true

[[files]]
file = "mods/overlaytweaks.pw.toml"
hash = "024c3d1085caad8d8846a25021ae6cfc693c1cdb4c2652d35fc257c92b15f7cd"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "0a8dabba5c14c717c159d4815c742c64eb3282d2dedcac562e1849b83c60b3e1"
metafile = true

[[files]]
file = "mods/particle-tweaks.pw.toml"
hash = "8a8c18221d9c969dc9e0b280a78019752f0c632ae390e4373cdab28a7bd9ed4b"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "30b4f717772625160c5ef1735dcafc0d1e807a46adf06f1bbf4e25a607d0c976"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "d87e145e22d71abb02e46f8b33e5b262165f81508cea78a45814052cd0e9f792"
metafile = true

[[files]]
file = "mods/rendertweaks.pw.toml"
hash = "3c77610b5fd94fb53c14ba1b8b40c6be982b843ff8507d82563ee3a8c307b7b1"
metafile = true

[[files]]
file = "mods/reward-claim.pw.toml"
hash = "ea2dc96f31bb9fc2609905e27da6175d1866cf7b87e9f30866ff14da3bfae1df"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "1b3d3e75ecdddc40fd913844421ff66ee3bdaeb2e12aee72f4c9b0df888718b7"
metafile = true

[[files]]
file = "mods/scoreboardtweaks.pw.toml"
hash = "6c8cdd959a240905875ae7f699c529534c2f9fbf8d28372b0d2aa861bfb6f3a0"
metafile = true

[[files]]
file = "mods/screencopy.pw.toml"
hash = "1286090509d0c5d2e84b434940c036c06dbc96636d7d4941369c51a40a48a479"
metafile = true

[[files]]
file = "mods/scrolltweaks.pw.toml"
hash = "b388da17ff7f44332f534565ce8cbff232b8d8bbf06c84daaf467fe5d69b8bcf"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "7cd6c4636e9da008ea36bd84645072deddc42459225e6012f2db85febeae13db"
metafile = true

[[files]]
file = "mods/secureskins.pw.toml"
hash = "7207102ab628e35d741d154abba6c6cdcd5540f69b86d828162f7ca09e9214ff"
metafile = true

[[files]]
file = "mods/server-pack-unlocker.pw.toml"
hash = "ba206189311792c2258aea66c7a2769bfd36a520435a796b6df1ff6a50b16e08"
metafile = true

[[files]]
file = "mods/simple-nick-hider.pw.toml"
hash = "80a9f298408b0ed7501d26c828109f669ac4bfc2ae2e820f4e39a1d0e5e88313"
metafile = true

[[files]]
file = "mods/skyboxify.pw.toml"
hash = "cab8a45d8c4822f5f7c2d5b5764e8949d2af13a1cc3762d5937e5be27065e9f7"
metafile = true

[[files]]
file = "mods/smooth-scrolling-refurbished.pw.toml"
hash = "260d167b209f308cbaa0f4d2ef22babc12457949fdc48eaaa8dd8cd0689c4b1a"
metafile = true

[[files]]
file = "mods/smooth-skies.pw.toml"
hash = "385d08a8eb2dec67e3cfde8d5f0d52761228c633b33fdea8428f68de8f3c0687"
metafile = true

[[files]]
file = "mods/smuc.pw.toml"
hash = "27ebe966070a007132ebaee0122277b83a2754c6f807d1932d8d2bb6d563e84e"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "ee6bb4c7678372ef35f737a583bd9640c50a2321de31f675f696112c5b75c529"
metafile = true

[[files]]
file = "mods/symbol-chat.pw.toml"
hash = "6bad64c8a859431c2d6f4ac1282ec98dadad39885bd3744e572b77ea0397c387"
metafile = true

[[files]]
file = "mods/tabtweaks.pw.toml"
hash = "606376d8fef64e7d599ce670d18c18b8cb148b85692f35d9044fd4c042cfe382"
metafile = true

[[files]]
file = "mods/text-tunnels.pw.toml"
hash = "488b6a0e9b33834691be5c52212e25d0f389f562637261e4b872b37664fd07a5"
metafile = true

[[files]]
file = "mods/titletweaks.pw.toml"
hash = "57d0020b4b6036c92a39fc6a8e9c360129f37eafd52ffea88bcc38d54ce3bfd8"
metafile = true

[[files]]
file = "mods/tntime.pw.toml"
hash = "5a1de8c4fac6fe371abc19d4edcf9ba15db41f76f70c11c65e9dff5229f48a8a"
metafile = true

[[files]]
file = "mods/tooltip-scroll.pw.toml"
hash = "4a18f96f71e9982faaaee390cb67e8ae7d3ae73c28b79525cd85688f90724f91"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
hash = "1f627a582a9ca18cc0e9e6b5cc829c211316675904186b91e163e7df9e1e60ef"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "7fff4bcf0961f81028d54b6ec9abaf3b4de6a51688d28c8ae2d35285873b4e27"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "3318a261d08c017118965a76f3232c96ba85c625acc43b26a040c1c5b04505d1"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3a0cfb6034a14d65f050278d2580c7166a895e7a37d8e512e2cc9deadba74107"
metafile = true
