hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "342dbfea1eb1da77369eb859ef22afc55732a7cdeface9a46b63bf4c1c4007d1"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "16b4d7b5351a21c6e0e9b32b2f4cf0ea91486c30c186bf9e3e741b13543b0d8a"
metafile = true

[[files]]
file = "mods/amecs.pw.toml"
hash = "d7d434777c1338b13b09f49a6540f6722687c512debd221e34723cf6790056a0"
metafile = true

[[files]]
file = "mods/better-elytra-render.pw.toml"
hash = "b8dfcee3acd2b482738d2c55c63525ce058af1d92a62b1b0f2622ae3873a0919"
metafile = true

[[files]]
file = "mods/better-screens.pw.toml"
hash = "40b7b9e17abe33a7d9ca6cec7a9d3fce204838e5cedaabc8ab6bff197a47149a"
metafile = true

[[files]]
file = "mods/better-selection.pw.toml"
hash = "51e05f70450310a8f893f2b44f99103bcb26a5bb9323fded221039b2eb925c62"
metafile = true

[[files]]
file = "mods/black-bar-concealer.pw.toml"
hash = "4179ab7808c1a11cbac8210bf36b326b3f5abd49025094c5ff4b62265e10d809"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "b065996c94b15f2b52bf944f4fccaf6fe2c6df8dd27c1667578ff62540a62939"
metafile = true

[[files]]
file = "mods/centered-crosshair.pw.toml"
hash = "ba4bf3fa860fb72b491ca8970703e37318aa5c6bd0a248f7af2a7ba3490c7fac"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "38f9517d9508846814b869adaf909846c95066e77ed381124abd3e661e7ce687"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "bbf28818ac59c19583f03d516a86b508e7da7a591c28d071c4e53effd4865bf6"
metafile = true

[[files]]
file = "mods/confirm-disconnect.pw.toml"
hash = "f970823279d7227eb25daeee04822777c0abd4f0965ff2bffa2357fad9fe7ab9"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "215f81b9480417e7e55fc70c6091129bfcd8e46da57cfc702603882e9a566cdc"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "e2ea9fbb81fb80bb8a65f398e95af99c7e6fcc060a1da5a8328d0adad702b6bc"
metafile = true

[[files]]
file = "mods/crosshairtweaks.pw.toml"
hash = "efd3b8e29e4841dfdc797c7e70e6d1d85bc936ab9e5ba49451c730e88246ef83"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "2114081f8c55f654dad9015d85347ed440c7f0ff3f115f64b94e850337d2d920"
metafile = true

[[files]]
file = "mods/dark-graph.pw.toml"
hash = "d50c62ce2c560fd5a6ab855ecb6e706ccc068ca07f69f36a964892ffa87f952b"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "8f01c4961076f709b58bf30eb8715f0eb4a7ab92e55ef4eab6253abd337cc3eb"
metafile = true

[[files]]
file = "mods/droppeditemtweaks.pw.toml"
hash = "e36f701725f84fe8a3f0679ccad8c8d10c50306b57b96c9fd82c16cf913e7516"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "60722287e7a1f3b7ca9aba9893ecf0db65822cf0af055bb44d423a79508c09ad"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "a2db8dfeb2eafb1cb8bbd08bd2d23a7c58c6bd8b6d5b9bfac759edc342c460e0"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "5698aab00158fb0ca7721c8b5201879a21a0657220652fedae19a7fa4d86bcca"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "3f37a4e78e0f939ca097ef8d80a618bf14007d94e89512c285f8ac8732fdcbd4"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "ca2147ccc6cd2a9d8ee484dd796ae8e1c5de42551c9366f2d09915bbe1c0002e"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "344ca02ae26f79bc11dc6d65751503613964da6761fcda5a33291dc7d8aae36f"
metafile = true

[[files]]
file = "mods/firmament-packet-fix.pw.toml"
hash = "a156c09bb370238b6bb7f6195de105486e0e1b9d634ef22d8f2710e797e0fbdd"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "c4b2f70f7f520a4854522e5e028265832fe2759c9dba3dba9c7eeb185fb8cbc6"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "99c250d5c3812b19b8114340d51cb5af63d92b5dec954be73b3c729dcf5cf3c9"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "0f56ddc3a39115afee2da77ff35d9bff1e65a8aa757306f22db43be8d35e5b30"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "94546366fc21817124c0bd14bf120284af8932e003715494f6d2423ce222d023"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "f4504187b6b7bea442fe8afd03818657ba5f28757e80afbaa2fbf160540f689b"
metafile = true

[[files]]
file = "mods/mountopacity.pw.toml"
hash = "72d9ef180b0625a5c1cc59a855e5e3b6df8d8a4f4ed9008f26d7d7cacbb9756c"
metafile = true

[[files]]
file = "mods/nametagtweaks.pw.toml"
hash = "f7fd4179a1d4fd85058be89b093395ebb3477fcf576bda2cd914e1e9b38d7f05"
metafile = true

[[files]]
file = "mods/nbt-autocomplete.pw.toml"
hash = "2ef9ab9aaf64752acc6b3e75d7f5127896d38bd837651cf3479f8ed28ee2f2ce"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "c44b4b553fec482a711b65bfc692c4d83ebe616cddd53d70ea1a9d976380104b"
metafile = true

[[files]]
file = "mods/no-chat-restrictions.pw.toml"
hash = "4ff1e551d7d0f0c0cf6068fa215a1afd63c66f688288e7c8fb59babd58e60065"
metafile = true

[[files]]
file = "mods/notsoessential.pw.toml"
hash = "78c50dfb4a64563c21a9716062112e5ec8aa79cc703e2945402d53ec0ad9b9dd"
metafile = true

[[files]]
file = "mods/numerical-enchantments.pw.toml"
hash = "93d23b02f3f9332665894105c7626a1e11a260ed08e2087462aeedb6f8d88e3b"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "cb3555d4858820ab6e0914e846e848d42746bd843e632cce1458e89af96235de"
metafile = true

[[files]]
file = "mods/overlaytweaks.pw.toml"
hash = "024c3d1085caad8d8846a25021ae6cfc693c1cdb4c2652d35fc257c92b15f7cd"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "0a8dabba5c14c717c159d4815c742c64eb3282d2dedcac562e1849b83c60b3e1"
metafile = true

[[files]]
file = "mods/particle-tweaks.pw.toml"
hash = "8a8c18221d9c969dc9e0b280a78019752f0c632ae390e4373cdab28a7bd9ed4b"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "b8a952a04286ba739ab658fecadaa7974d3a7ea6ec8199056eed151448049429"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "d87e145e22d71abb02e46f8b33e5b262165f81508cea78a45814052cd0e9f792"
metafile = true

[[files]]
file = "mods/rendertweaks.pw.toml"
hash = "5dd3ea1f1c4e822e75046d9dbd1dd391aca9bfe1ab49862e16b5407b76c5b420"
metafile = true

[[files]]
file = "mods/reward-claim.pw.toml"
hash = "ea2dc96f31bb9fc2609905e27da6175d1866cf7b87e9f30866ff14da3bfae1df"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "aabc3115b6b59c076a580386f6ab81813d3238b0723a1b6dc5761fff63c0d9be"
metafile = true

[[files]]
file = "mods/scoreboardtweaks.pw.toml"
hash = "9c009a8efd6da4ea1e05e4d529a567c8eb0455a424a610d40c191eef6a3f447c"
metafile = true

[[files]]
file = "mods/screencopy.pw.toml"
hash = "6b7368094038741a913862168d864c6a792c9c690b11f096ea784ee2556320e2"
metafile = true

[[files]]
file = "mods/scrolltweaks.pw.toml"
hash = "00fb117a2ba12716346c78de57d1f27799e57a4b78134b25a2dfb1674907791b"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "cb737f68fe70474c3f3cd67347936db7078f95c8cb394a7d651c26d9de532c11"
metafile = true

[[files]]
file = "mods/secureskins.pw.toml"
hash = "6f86801967b3eb67870da395d7138ea0644719373fea8d2da2182587586115c3"
metafile = true

[[files]]
file = "mods/server-pack-unlocker.pw.toml"
hash = "a5c0a91308a5dba8a879c38d9defd9bfb4cbb78001252bd33bcb90f2fc932247"
metafile = true

[[files]]
file = "mods/simple-nick-hider.pw.toml"
hash = "9c1edf2bcbf1372e937bc5b101135ad27d1960744e0738e8be528877132987e8"
metafile = true

[[files]]
file = "mods/skyboxify.pw.toml"
hash = "bc22739b187fa5d217416a73b6206ff2e5eb5554bd882d655c6e397b01bf744f"
metafile = true

[[files]]
file = "mods/smooth-scrolling-refurbished.pw.toml"
hash = "384d6723c324e599e89081c28c4715ec49fc0fd6d104daa5cce9f0ea55e1deb6"
metafile = true

[[files]]
file = "mods/smooth-skies.pw.toml"
hash = "385d08a8eb2dec67e3cfde8d5f0d52761228c633b33fdea8428f68de8f3c0687"
metafile = true

[[files]]
file = "mods/smuc.pw.toml"
hash = "e55d7fbcb0c54f702f8a09fd5327ecee7effd792dbbc8792f460288d303c22ce"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "ee6bb4c7678372ef35f737a583bd9640c50a2321de31f675f696112c5b75c529"
metafile = true

[[files]]
file = "mods/symbol-chat.pw.toml"
hash = "6bad64c8a859431c2d6f4ac1282ec98dadad39885bd3744e572b77ea0397c387"
metafile = true

[[files]]
file = "mods/tabtweaks.pw.toml"
hash = "606376d8fef64e7d599ce670d18c18b8cb148b85692f35d9044fd4c042cfe382"
metafile = true

[[files]]
file = "mods/text-tunnels.pw.toml"
hash = "488b6a0e9b33834691be5c52212e25d0f389f562637261e4b872b37664fd07a5"
metafile = true

[[files]]
file = "mods/titletweaks.pw.toml"
hash = "57d0020b4b6036c92a39fc6a8e9c360129f37eafd52ffea88bcc38d54ce3bfd8"
metafile = true

[[files]]
file = "mods/tntime.pw.toml"
hash = "5a1de8c4fac6fe371abc19d4edcf9ba15db41f76f70c11c65e9dff5229f48a8a"
metafile = true

[[files]]
file = "mods/tooltip-scroll.pw.toml"
hash = "9067aa4d3e87b36321b5061d8407f723f235778978b0a5f7863e9a5601bf732e"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
hash = "1f627a582a9ca18cc0e9e6b5cc829c211316675904186b91e163e7df9e1e60ef"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "7fff4bcf0961f81028d54b6ec9abaf3b4de6a51688d28c8ae2d35285873b4e27"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "3318a261d08c017118965a76f3232c96ba85c625acc43b26a040c1c5b04505d1"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3cf9454db44da1445fe9e55aa8e4a488faac04e5d22b4189425f3ce0572671f1"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "d2a5ab1ce39eaba6368ab927280bf36a4487ee8d4d614b411a22814df5da2f7a"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "482fdbf07912604af128c6bddbd47309b094100deb71b43ab27a6ae18bd56f1e"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "ce28a9661864b61137f595f47ac89297f0872d1e814f0c41ee5f4ee3d5a71d25"
metafile = true
