name = "OneClient 1.21.11 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.21.11-fabric"
update-url = "oneclient/generated/qol-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ded9854dcc9eab2fe5d0475e404386e43a2462f24e14d905542f019c7ac88315"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
