name = "OneClient 1.21.11 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.21.11-fabric"
update-url = "oneclient/generated/qol-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54334c58bcc1a2d4b9d0b9d3d9eb7cd175b0f22b9d8831e6a08c547fdcb29f34"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
