name = "OneClient 1.21.11 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-1.21.11-fabric"
update-url = "oneclient/generated/qol-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e6bf2e391bb3747367d6e04d1a24ee17fe6105577f66e93fa329e1bdfd6dca8"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
