name = "OneClient 1.21.11 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.21.11-fabric"
update-url = "oneclient/generated/qol-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f51e2974e03bb4b781cf0f55185f11b60f121a17f54b77984f84674689b5bf7"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
