name = "OneClient 1.21.11 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-1.21.11-fabric"
update-url = "oneclient/generated/qol-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46de3044449e44ca4bee52567e56b38930825ba2d8bf2cfd3aa2793b12e2d420"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
