hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "342dbfea1eb1da77369eb859ef22afc55732a7cdeface9a46b63bf4c1c4007d1"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "b8c52ee06f6319fc2249c2f9fdc21a8946baa8651daf32542e2eb49b0d9aadd1"
metafile = true

[[files]]
file = "mods/amecs-reborn.pw.toml"
hash = "6f327aea33c7ef9658cb53e1c7b6e910ab07c22f78d6bb7ce2f2a50b0f6c7e9f"
metafile = true

[[files]]
file = "mods/animated-typing.pw.toml"
hash = "7b0e797e43631250247057eeeaec71f6d4c85098902e2d7c20dacb97a20436a3"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "6a5ac1308522e6e7ee8226ab4b17b1c518640f1d1f2e49281eef0951520cd548"
metafile = true

[[files]]
file = "mods/better-elytra-render.pw.toml"
hash = "a540b5825e250e62ddb81faeda96ca6a7c8320827c5e8edb7c9d9901c896ee7b"
metafile = true

[[files]]
file = "mods/better-screens.pw.toml"
hash = "84fe63c50c55a03fa2c9e0bbe807c08bbad5948afb737d56abe0d397a0dda716"
metafile = true

[[files]]
file = "mods/better-selection.pw.toml"
hash = "0201825029921bdd8b4b276ca147fd1e1eff5e983b114a89c2060628949257f0"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "ab8ed6bf9cbfe35cdf392f46faa0f48dd4fc8a9869cf08ed1a9b59b9712f89be"
metafile = true

[[files]]
file = "mods/centered-crosshair.pw.toml"
hash = "83ffa074e9b6521772c3d7398490467ad3289d440783d64450e3e3fa3cf7e751"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "c086f624a1538a1e8ea1d5f36a1ef75f68746be086955401fc7a0cec3910c6fb"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "76b6fda698cdd336a97069ad637d51a1687cad4f9e3fa393dca7464531320280"
metafile = true

[[files]]
file = "mods/confirm-disconnect.pw.toml"
hash = "51fede9c41431704bd4204f7a2bd1f8a40530769eb6bfea018920aa71a9588f9"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "84b458c31a8b25b23e1d5216ff384953fff2f497636ea292a6cd9ee2e654a7ca"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "a4ee2ccf79407c102132f96ae6377547ed4fe883fb18a38189f9a45c28ce8989"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
hash = "0a09c0ea83426d66093dffc4632701ae71a1538f39bd20de8c64d596ea1e0011"
metafile = true

[[files]]
file = "mods/crosshairtweaks.pw.toml"
hash = "395e003a1e09f920cef5788706298cff5f1c24336d39ad6e283f6eb339e05168"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "c10c22270cc0a646eb698acdd5a7e3a4a13167fc5c635172796b25bc2c870cef"
metafile = true

[[files]]
file = "mods/dark-graph.pw.toml"
hash = "d50c62ce2c560fd5a6ab855ecb6e706ccc068ca07f69f36a964892ffa87f952b"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "8f01c4961076f709b58bf30eb8715f0eb4a7ab92e55ef4eab6253abd337cc3eb"
metafile = true

[[files]]
file = "mods/droppeditemtweaks.pw.toml"
hash = "1d30aaf732375176cbfe8ae46bf6e759ba04ee7243c6b8b1bbac213e7fc8d0ae"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "a6006adcd33bcbee7f3efe42addff0f399b2394efe2f3d2abfcc3c226aac1e45"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "8ecf0a7ad9620c211710218e3376ef7fe1efcc9e69217b24f6cf5014e25518c1"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "aad7486d784c2274e24f60edd30e2c45bb6e56b9a1eb7fb78d74a45b9bd89ea4"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "e062536eba743b069de67adc6b86aa828af415f12cc03267e0f2151bea1de781"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "436fece36e8837e8922762b74763f5600d0190d36c5f7974b02cc06a78a95c7b"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "344ca02ae26f79bc11dc6d65751503613964da6761fcda5a33291dc7d8aae36f"
metafile = true

[[files]]
file = "mods/firmament-packet-fix.pw.toml"
hash = "3c7b15cdedbcf1620247e696ea4c571bb89a5a2e45fd3e3a46140bef660ca7a2"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "675958b7271c3dcff092f7d424166b69e21c4a171dbc9e7f9eb1ac307e32cf99"
metafile = true

[[files]]
file = "mods/hypixelautotip.pw.toml"
hash = "8a59d8637f16848e695306086fcc9a5b642798d26c53e34e729eceaf062005d9"
metafile = true

[[files]]
file = "mods/jsonem.pw.toml"
hash = "210d8df7c828ff25f6dda797be006dac87f51e17d028222712ff2c358d3d96d2"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "75998ace3f1ddc3b973ce2e79d91fdadbdc3f393bb107c742c28f052d185e90f"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "94546366fc21817124c0bd14bf120284af8932e003715494f6d2423ce222d023"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "075319af723930be4c5d05386013d16ea9535574e82f80f34c0560c212908439"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "689ac564c525e0012a17bbba810c8dcd4262ff718fdf0d1611043be7d391e213"
metafile = true

[[files]]
file = "mods/mountopacity.pw.toml"
hash = "aa4241cba655974c156ae0c24901ddf2bbd43cd74de0d484dbd68c105c382118"
metafile = true

[[files]]
file = "mods/nametagtweaks.pw.toml"
hash = "1aeb1bfc3be697b24570edaf1d8218ddb480fa141f65edbda12772cf7aee7742"
metafile = true

[[files]]
file = "mods/nbt-autocomplete.pw.toml"
hash = "c08e7c09f9baa6a7d55041d6c438c7183fe66d3bd496900c4f1113a779428a4f"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "9fbfdf31300b4716c8a5975e8f84c0b171f8d099ec5bdda86814618d66c378c3"
metafile = true

[[files]]
file = "mods/notsoessential.pw.toml"
hash = "78c50dfb4a64563c21a9716062112e5ec8aa79cc703e2945402d53ec0ad9b9dd"
metafile = true

[[files]]
file = "mods/numerical-enchantments.pw.toml"
hash = "0d621b7e114b6685a43ef086b001766075eecea1f6463c322aab5bd4ab9bf7ce"
metafile = true

[[files]]
file = "mods/one-click-join.pw.toml"
hash = "5ae3038167b0a5b6bf351e249324f30c37ee9b6d82ca6847debde9853d5555d4"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "716ae703cea46c716ae86d4e612e5d29b0604af8b26f4ef7c2c7e00290542a36"
metafile = true

[[files]]
file = "mods/overlaytweaks.pw.toml"
hash = "7498861811d5f843463dde647b02169ea2c0fda83b8e80a8d6450ba5b8a688ed"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "32ef9777281ad976739c23d0df02d71935a98aabfd0a99850c59631a8fdd4d70"
metafile = true

[[files]]
file = "mods/particle-tweaks.pw.toml"
hash = "dcd6051d35ea13245da6f6e2d1ecd6633e18d596fe9561a12c61103f48615218"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "37bf604557da1fe6ba043175b454db3e4d34924979fd9f79f7d3ebf29b80c24c"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "17281d530accc64e4fcfc204b09985bff0cf8f54cb4f9d48e03b317a5dd9c1ab"
metafile = true

[[files]]
file = "mods/rendertweaks.pw.toml"
hash = "6ec9af3806f37364eaa5ed356c13588be0cbb85981b4810a93bc4d9217628b06"
metafile = true

[[files]]
file = "mods/reward-claim.pw.toml"
hash = "1554dba60c33db392c8767456ffda000dccf564285d6327d493bd28f5b2a79d9"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "ff65bc784914d8627b8769460baad3e0534368666a573c5c26b3bed349104a58"
metafile = true

[[files]]
file = "mods/scoreboardtweaks.pw.toml"
hash = "9c009a8efd6da4ea1e05e4d529a567c8eb0455a424a610d40c191eef6a3f447c"
metafile = true

[[files]]
file = "mods/screencopy.pw.toml"
hash = "6b7368094038741a913862168d864c6a792c9c690b11f096ea784ee2556320e2"
metafile = true

[[files]]
file = "mods/scrolltweaks.pw.toml"
hash = "00fb117a2ba12716346c78de57d1f27799e57a4b78134b25a2dfb1674907791b"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "2f181d88b38f019fb919db710b95d4fdee65f60520ab47b34aa5b60628606674"
metafile = true

[[files]]
file = "mods/server-pack-unlocker.pw.toml"
hash = "a5c0a91308a5dba8a879c38d9defd9bfb4cbb78001252bd33bcb90f2fc932247"
metafile = true

[[files]]
file = "mods/simple-nick-hider.pw.toml"
hash = "7931e2b3d22f15710a2653d0f90d6ce096fa16e31aa08ca4ce7cbe1a593dcbdf"
metafile = true

[[files]]
file = "mods/smooth-scrolling-refurbished.pw.toml"
hash = "083ffbb2a1b30093ae2eea39981142619a7ce553ba1b71d7cdc2ab40c4e18ae7"
metafile = true

[[files]]
file = "mods/smooth-skies.pw.toml"
hash = "33fa94861c171c47f31823443f6542af2454b065311b6d8fe6bdc9c5a97c6946"
metafile = true

[[files]]
file = "mods/smuc.pw.toml"
hash = "e55d7fbcb0c54f702f8a09fd5327ecee7effd792dbbc8792f460288d303c22ce"
metafile = true

[[files]]
file = "mods/sound-physics-perfected.pw.toml"
hash = "32c01fbad8ba133a8cf9447595eabec1c57069102be11378a7722d81182eb6a4"
metafile = true

[[files]]
file = "mods/symbol-chat.pw.toml"
hash = "cc5c389279eee0b3d50d8e9e03b735de859796cc8242cf0f61bdad46e94f3f56"
metafile = true

[[files]]
file = "mods/tabtweaks.pw.toml"
hash = "c4fdd0601289082d2b87d0e755e7fe5941d3d54e3733275aecf35c174785c081"
metafile = true

[[files]]
file = "mods/text-tunnels.pw.toml"
hash = "d8a91eb7128084df99c44fd9cc757e9dcdd24424038a1e70a7a96aa30b0e847a"
metafile = true

[[files]]
file = "mods/titletweaks.pw.toml"
hash = "0aae38162b1b7270a40774a7ee6256f0d1e1a0dc06b4177d212b6c339b3448b7"
metafile = true

[[files]]
file = "mods/tntime.pw.toml"
hash = "11892cd0067ce8dd140ea2a9770be51e9a3df8c573cadf7f35f4cf1005b79243"
metafile = true

[[files]]
file = "mods/tooltip-scroll.pw.toml"
hash = "b3247c5f20d5d64a31fc6afb23b7f67445d59155da0554ef3912f12bb3509138"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
hash = "04ba099ab1011f81a3a2ec610c85bef572abb0757913379a1b09d19351f651e7"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "33377901e12cbd7c4bac6dd56a5d3a45180b6969052cd8de295ff74c50908d69"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "5d6c8e3f1c8cd5cd073a73f2b09edcf4a8002350ad1c5ccaba640e86540f6458"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3cf9454db44da1445fe9e55aa8e4a488faac04e5d22b4189425f3ce0572671f1"
metafile = true
