name = "OneClient 1.21.8 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.21.8-fabric"
update-url = "oneclient/generated/qol-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2973f6e0a103cd686f2663b9ce3a12e5aa592fabf59170180201e18bf463a15"

[versions]
fabric = "0.18.4"
minecraft = "1.21.8"
