hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "447d246397d63f66f9f22bf233f999cbaf3dcfb82af3209cfece9bee206dff23"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "8efbb45ea6e576a6c8f2d08c5e0e33e7e372a09da33f7dfced25d11e14f92a6f"
metafile = true

[[files]]
file = "mods/chat-impressive-animation.pw.toml"
hash = "1ba297564b0ad5a8dc9711a6af15c29ba15bd667b1a80405c29601f39692c222"
metafile = true

[[files]]
file = "mods/chatpatches.pw.toml"
hash = "5b419560688e93e2d02daabce5ce379419c958acb2db521cb7123de7cb2eec1d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "bbf28818ac59c19583f03d516a86b508e7da7a591c28d071c4e53effd4865bf6"
metafile = true

[[files]]
file = "mods/detail-armor-bar-reconstructed.pw.toml"
hash = "4f7eece98ebe6eccba3811cb425f6de2fa4d0a44fdd3e4763de6517b27405e3f"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "ca2147ccc6cd2a9d8ee484dd796ae8e1c5de42551c9366f2d09915bbe1c0002e"
metafile = true

[[files]]
file = "mods/inventoryhudplus.pw.toml"
hash = "5222c2b37ebc6074973d82029ee228e40e3dfc8c8ab606b9ee1bc112b0dc39e1"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "0f56ddc3a39115afee2da77ff35d9bff1e65a8aa757306f22db43be8d35e5b30"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "f4504187b6b7bea442fe8afd03818657ba5f28757e80afbaa2fbf160540f689b"
metafile = true

[[files]]
file = "mods/ukulib.pw.toml"
hash = "71550d18d84d3f045ffb0ac0dc0ad020d6fa1f263cb60c1fd1aa9024f58229b1"
metafile = true

[[files]]
file = "mods/ukus-armor-hud.pw.toml"
hash = "385939d7ad658d8587a7a39f92feca35f998ba7795766588eb4e109c40b8b20d"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "1765c84b093eba73f278a6f7af45f722445f35f08f8f9c103e6df42c28446f8e"
metafile = true
