name = "OneClient 1.21.11 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "HUD"
id = "hud-1.21.11-fabric"
update-url = "oneclient/generated/hud-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbf531e32abf633a28de96882609805c8da3d3f522c9a1d73a96e811fae0e85a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
