name = "OneClient 1.21.11 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "HUD"
id = "hud-1.21.11-fabric"
update-url = "oneclient/generated/hud-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16cca695ba8e700d0b4196da70c4df4b12c5cd3cfad44147a4cc3347e0e5b780"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
