name = "OneClient 1.8.9 Forge [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.8.9-forge"
update-url = "oneclient/generated/skyblock-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a07b783463e1738fcc50a3c4cd70671cc34ad91cf78725278341fedd03f686ee"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
