name = "OneClient 1.21.1 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.21.1-fabric"
update-url = "oneclient/generated/pvp-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0122e07c88dd22743d20430bad6717f952ef62e57f39539b538f67e5d23c7baf"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
