name = "OneClient 1.21.1 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.21.1-fabric"
update-url = "oneclient/generated/pvp-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb1dfd2339b3e42497a8dd85180016ed912fcde399e733a0387481bf27723617"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
