hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "342dbfea1eb1da77369eb859ef22afc55732a7cdeface9a46b63bf4c1c4007d1"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "f3e5bba1fff93770047b3a9d19585a194c20d5c4f9a30822e8be243e232cb147"
metafile = true

[[files]]
file = "mods/amecs.pw.toml"
hash = "d7d434777c1338b13b09f49a6540f6722687c512debd221e34723cf6790056a0"
metafile = true

[[files]]
file = "mods/better-elytra-render.pw.toml"
hash = "b8dfcee3acd2b482738d2c55c63525ce058af1d92a62b1b0f2622ae3873a0919"
metafile = true

[[files]]
file = "mods/better-screens.pw.toml"
hash = "afcad2870c7a312dbef35c4d59901d24fe3829f1ddef0d29fe4ed2b7dfd1d04c"
metafile = true

[[files]]
file = "mods/better-selection.pw.toml"
hash = "53e360245f8b4f2292191f9a8eeb20bafde4cdb5e38cd62bb9d16ca80a3c6374"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "f982807379d8012881c633a49f2df6a864b6b8c489b3393e5b56c70dc3e45b23"
metafile = true

[[files]]
file = "mods/centered-crosshair.pw.toml"
hash = "3eb136919b01f3a601f5e58d0cae6957734312147880121b0ae765ff53c416a7"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "03d88f6f85cb0f1b693d5fa0011dc87382a0af3526bc20d21e0d348f8d584bed"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "9c22bad4f0d606f92ce105da00204c29aa2b356401cc5d1088f63bb02f90d351"
metafile = true

[[files]]
file = "mods/confirm-disconnect.pw.toml"
hash = "f970823279d7227eb25daeee04822777c0abd4f0965ff2bffa2357fad9fe7ab9"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "f0a3b09afbf01eae5f5f8d0422475793b41667fb1189c0ef2def4f5d10cfa7b7"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "2be8708c48474a7e7308102e09d088793dd92747e384922b57a2b5a86bab5641"
metafile = true

[[files]]
file = "mods/crosshairtweaks.pw.toml"
hash = "efd3b8e29e4841dfdc797c7e70e6d1d85bc936ab9e5ba49451c730e88246ef83"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "c10c22270cc0a646eb698acdd5a7e3a4a13167fc5c635172796b25bc2c870cef"
metafile = true

[[files]]
file = "mods/dark-graph.pw.toml"
hash = "d50c62ce2c560fd5a6ab855ecb6e706ccc068ca07f69f36a964892ffa87f952b"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "8f01c4961076f709b58bf30eb8715f0eb4a7ab92e55ef4eab6253abd337cc3eb"
metafile = true

[[files]]
file = "mods/droppeditemtweaks.pw.toml"
hash = "bc5e1685691b2c39a59e85bc5b9a4ccc6745fa467714602b96d20fe1fb1a4464"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "60722287e7a1f3b7ca9aba9893ecf0db65822cf0af055bb44d423a79508c09ad"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "ef1763d4a134fb0ebece9c3900461cd34f730ab50355c6aae242f6982003307a"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "9e5d401798e701b6dc8cf81f9671b6d147dd94fe4159e5ee7b7a3af63b31b0f9"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "3f37a4e78e0f939ca097ef8d80a618bf14007d94e89512c285f8ac8732fdcbd4"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "71057ffacb79edc48ef50b33ba506255e3da4ad48e8d0eaa4635368097567ba9"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "344ca02ae26f79bc11dc6d65751503613964da6761fcda5a33291dc7d8aae36f"
metafile = true

[[files]]
file = "mods/firmament-packet-fix.pw.toml"
hash = "a156c09bb370238b6bb7f6195de105486e0e1b9d634ef22d8f2710e797e0fbdd"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "c1f2a3de3583dfc64723e1415ca43dd4ec73dff15c3ba9f608aaf86f3b9e59c0"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "5d75fcca2b50cf123b7cca0706ff75ed74821d544cbf8e6f1a9fe8830195a9c0"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "91ea5cfda5dfc87a5ed23c5db726afd831e26f4cfbf7be0fe07c3d1a495c9ba2"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "94546366fc21817124c0bd14bf120284af8932e003715494f6d2423ce222d023"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "26e47d11736b8d32991ec4ecd4ab9fea603d7597cbd737fd7b7b20760467f35f"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "94828f99c4d81ae74fdc9daa04a45bb1bdc030d89140f265c323e9f9d03f2d9e"
metafile = true

[[files]]
file = "mods/mountopacity.pw.toml"
hash = "1c55ed514aeabd5f8960e9ed554cc303a98bf2c845bc29d6cc6e4ab96085e650"
metafile = true

[[files]]
file = "mods/nametagtweaks.pw.toml"
hash = "f7fd4179a1d4fd85058be89b093395ebb3477fcf576bda2cd914e1e9b38d7f05"
metafile = true

[[files]]
file = "mods/nbt-autocomplete.pw.toml"
hash = "bdf6067f65863068f71585423bec6f484aef15503ceac63de4f06b69795ea817"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5b0d29129f8a63f9d565ce59de61ede12ac3f1c83befa13430b45f3fa1ccefe8"
metafile = true

[[files]]
file = "mods/notsoessential.pw.toml"
hash = "78c50dfb4a64563c21a9716062112e5ec8aa79cc703e2945402d53ec0ad9b9dd"
metafile = true

[[files]]
file = "mods/numerical-enchantments.pw.toml"
hash = "93d23b02f3f9332665894105c7626a1e11a260ed08e2087462aeedb6f8d88e3b"
metafile = true

[[files]]
file = "mods/one-click-join.pw.toml"
hash = "5ae3038167b0a5b6bf351e249324f30c37ee9b6d82ca6847debde9853d5555d4"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "cb3555d4858820ab6e0914e846e848d42746bd843e632cce1458e89af96235de"
metafile = true

[[files]]
file = "mods/overlaytweaks.pw.toml"
hash = "2b00dadb4be55f64e05ea395a4d91b47a4e6fd185e3fed0638d0b8aee2a10b7a"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "ec8c86e8e0e3b67e54523e4b862868192466c4e2e2691af5d73f69f18acf2eac"
metafile = true

[[files]]
file = "mods/particle-tweaks.pw.toml"
hash = "ed31d7202ebdcebf7cd0e518e0748c41b2cc4d6592407a5ac6104ecb03d790c0"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "402a07c427d26dedd573aadf8b0f0f72cb4b1f1d65eb8e311568d0b9074ba6bb"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "22472d2e8c9c800d82f9d136ac985bb21a664ab39c99ee0f7f736331ccb16576"
metafile = true

[[files]]
file = "mods/rendertweaks.pw.toml"
hash = "0c48822898ceb572329fea3fa108b568652235bafcd41fe7c7d479f656cb9b04"
metafile = true

[[files]]
file = "mods/reward-claim.pw.toml"
hash = "638e347dc49c50e5642d84de321c30c2c58776bbbd822c8e1c4de4f69d62f8b8"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "36044ab399f0a85c5bf90aa2bc28e0bf4fcb451e759983f39d54832a2cdd56e2"
metafile = true

[[files]]
file = "mods/scoreboardtweaks.pw.toml"
hash = "9c009a8efd6da4ea1e05e4d529a567c8eb0455a424a610d40c191eef6a3f447c"
metafile = true

[[files]]
file = "mods/screencopy.pw.toml"
hash = "6b7368094038741a913862168d864c6a792c9c690b11f096ea784ee2556320e2"
metafile = true

[[files]]
file = "mods/scrolltweaks.pw.toml"
hash = "00fb117a2ba12716346c78de57d1f27799e57a4b78134b25a2dfb1674907791b"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "41f4d77b2cbf3609352de2527bc667d3775a6d00678163247a31ee8345f8ac57"
metafile = true

[[files]]
file = "mods/secureskins.pw.toml"
hash = "6f86801967b3eb67870da395d7138ea0644719373fea8d2da2182587586115c3"
metafile = true

[[files]]
file = "mods/server-pack-unlocker.pw.toml"
hash = "a5c0a91308a5dba8a879c38d9defd9bfb4cbb78001252bd33bcb90f2fc932247"
metafile = true

[[files]]
file = "mods/simple-nick-hider.pw.toml"
hash = "9c1edf2bcbf1372e937bc5b101135ad27d1960744e0738e8be528877132987e8"
metafile = true

[[files]]
file = "mods/skyboxify.pw.toml"
hash = "983f41d84443e4c49feba806b4b670de1927326cf4d3ccfc0e326b517e89aedf"
metafile = true

[[files]]
file = "mods/smooth-scrolling-refurbished.pw.toml"
hash = "384d6723c324e599e89081c28c4715ec49fc0fd6d104daa5cce9f0ea55e1deb6"
metafile = true

[[files]]
file = "mods/smooth-skies.pw.toml"
hash = "8bef6b4dbaaf539e8f392071a2f9210a9c7bb355c30f5da6faf97fb79a8f497c"
metafile = true

[[files]]
file = "mods/smuc.pw.toml"
hash = "e55d7fbcb0c54f702f8a09fd5327ecee7effd792dbbc8792f460288d303c22ce"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "5eaeb16e61a8bb9452c87f5ad5e6473a704f3ee56f7f12db27019a14c2a4904d"
metafile = true

[[files]]
file = "mods/symbol-chat.pw.toml"
hash = "5d360793274d6e422e85395018ea675ef0f6d023b74624809c1262da07b3967c"
metafile = true

[[files]]
file = "mods/tabtweaks.pw.toml"
hash = "235add68ed0e4c6a3bc12ad6f5e5108a934e1b859e855fbad459af2cc669ff57"
metafile = true

[[files]]
file = "mods/text-tunnels.pw.toml"
hash = "e98aeeffa9730ff8a365e4182ef2014037006149bd5a8fa38620a3bac4c71c0e"
metafile = true

[[files]]
file = "mods/titletweaks.pw.toml"
hash = "0aae38162b1b7270a40774a7ee6256f0d1e1a0dc06b4177d212b6c339b3448b7"
metafile = true

[[files]]
file = "mods/tntime.pw.toml"
hash = "ca252194ca88f2b9da857b94d644de6abfeac22da42cfc73d3aa61190e4bf558"
metafile = true

[[files]]
file = "mods/tooltip-scroll.pw.toml"
hash = "9067aa4d3e87b36321b5061d8407f723f235778978b0a5f7863e9a5601bf732e"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
hash = "a40e460fa6f93c466ba0208d18d960b287dacc1a47bb4cf62753ee0bef0b6e39"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "b41620c613b8955282f95366e1b2722e397e3b65a0a624eaa877177b6764d4a4"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "64bb3496588aa28a49fa60f981b1b25af24e135705ec53a4043e7c39e138d1d7"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3cf9454db44da1445fe9e55aa8e4a488faac04e5d22b4189425f3ce0572671f1"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "d2a5ab1ce39eaba6368ab927280bf36a4487ee8d4d614b411a22814df5da2f7a"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "482fdbf07912604af128c6bddbd47309b094100deb71b43ab27a6ae18bd56f1e"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "ce28a9661864b61137f595f47ac89297f0872d1e814f0c41ee5f4ee3d5a71d25"
metafile = true
