name = "OneClient 1.21.10 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.21.10-fabric"
update-url = "oneclient/generated/qol-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcba3c40e8f5771470e7cea6e7d6b3b7af19cbd0195d109f2449f8584360b165"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
