name = "OneClient 1.21.10 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.21.10-fabric"
update-url = "oneclient/generated/qol-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a5d2411335db5a10802ec5be3734a8a86f9fed95ff403370319b87c948244d2"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
