name = "OneClient 1.21.10 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.21.10-fabric"
update-url = "oneclient/generated/qol-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0f4e638709d36a1cba7a834e2ed2daaa7ea6b991ef24b2bfe631baa32c3b914"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
