name = "OneClient 1.21.10 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.21.10-fabric"
update-url = "oneclient/generated/qol-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f45f97c97988e6bdfe112bf83a00f3d8bcab7b535271eae4da66ea2f14d4a9d2"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
