name = "OneClient 1.21.10 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-1.21.10-fabric"
update-url = "oneclient/generated/qol-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8c5a94e8a594ec597cc5772b3bafc14745fefa1c56c095c7aad7dadc992e9bc"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
