name = "OneClient 1.21.10 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.21.10-fabric"
update-url = "oneclient/generated/qol-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1e89008a9c3ee21f605b84af5810476026e460f5e9af288517c78a3ef6092f6"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
