hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "9f5e2c21628ae0f03b5c1652501ca5cd04645207a88f44966c9d5bf8e3867297"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "8efbb45ea6e576a6c8f2d08c5e0e33e7e372a09da33f7dfced25d11e14f92a6f"
metafile = true

[[files]]
file = "mods/chat-impressive-animation.pw.toml"
hash = "bf91fcb3ec1c891d18b9c7443220f3dc463775a8607b6c9b2ef58a9c65020123"
metafile = true

[[files]]
file = "mods/chatpatches.pw.toml"
hash = "4f6557ded10a6c2c3d8e09f8a7328ccc6ace0363b6c172e3f16ae6f241f27949"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "9c22bad4f0d606f92ce105da00204c29aa2b356401cc5d1088f63bb02f90d351"
metafile = true

[[files]]
file = "mods/detail-armor-bar-reconstructed.pw.toml"
hash = "4f7eece98ebe6eccba3811cb425f6de2fa4d0a44fdd3e4763de6517b27405e3f"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "71057ffacb79edc48ef50b33ba506255e3da4ad48e8d0eaa4635368097567ba9"
metafile = true

[[files]]
file = "mods/inventoryhudplus.pw.toml"
hash = "02806a7e96ac7d97478ac89e270558075579480959168f09d4658d85e78ee8c4"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "91ea5cfda5dfc87a5ed23c5db726afd831e26f4cfbf7be0fe07c3d1a495c9ba2"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "94828f99c4d81ae74fdc9daa04a45bb1bdc030d89140f265c323e9f9d03f2d9e"
metafile = true

[[files]]
file = "mods/ukulib.pw.toml"
hash = "d32e4956bbad994ca3158002973bdde823042a90583ca7791c926eed6e905d26"
metafile = true

[[files]]
file = "mods/ukus-armor-hud.pw.toml"
hash = "b3c9963d61928e92c903cf216f91f5d57d65418ce755234e3b5f22056de417cf"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "e3208008761017ce98dabe50c37fad65f56ece476d6b678b7d1eb9eab39bc1a1"
metafile = true
