name = "OneClient 1.21.10 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "HUD"
id = "hud-1.21.10-fabric"
update-url = "oneclient/generated/hud-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3239200d0734aaa1349c3efeb2ba53157fdb4c8cabd5f289422f1ba191d239a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
