name = "OneClient 1.21.10 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "HUD"
id = "hud-1.21.10-fabric"
update-url = "oneclient/generated/hud-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "742d7279afb4d4d5e7776bfda0bf9b667ad3f679a89dfadf8904cc39754e51ba"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
