name = "OneClient 1.21.1 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-1.21.1-fabric"
update-url = "oneclient/generated/qol-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e07413380597d178cf9a07d55ccd3e11e51105881abc614e091a69e55cdbf3e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
