name = "OneClient 1.21.1 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-1.21.1-fabric"
update-url = "oneclient/generated/qol-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcad15ca1d5a2d0816b541a46c2b0eb7585a9e223649205998f578e1d17ada84"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
