name = "OneClient 1.21.1 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.21.1-fabric"
update-url = "oneclient/generated/qol-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51c2e98c6dde40a1d275f22cd52f2f2cba177f90d06f6cb931c19bd193bb7afe"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
