name = "OneClient 1.21.1 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.21.1-fabric"
update-url = "oneclient/generated/qol-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30cd69dd0aabcc6ce64c68af41653ab1a9731dfeeaf9190c53e0d0234eaaba97"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
