hash-format = "sha256"

[[files]]
file = "mods/animatium.pw.toml"
hash = "fc79d87617736b9fbec919351627081bd8e8f9440ef0c9da9d158cf6d052b907"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "dbc4960d91ef836961171d8a13f8adc29ee6df2c63ea23efeca96fc93e5d280a"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
hash = "c2dd467cc5398d147a3b0bef54c022b945f30d7e0217c87d716121f7e8d1d67a"
metafile = true

[[files]]
file = "mods/bettercommandblockui.pw.toml"
hash = "230fd9f75b3c7b1777bd186762bedf1af9fceb7673dbbb75342d930dbea012fc"
metafile = true

[[files]]
file = "mods/betternightvision.pw.toml"
hash = "a80e53a334ee3bd4c2ac4f06cf156a7843c91953e3724d7b0a64484010c68c1d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "9c22bad4f0d606f92ce105da00204c29aa2b356401cc5d1088f63bb02f90d351"
metafile = true

[[files]]
file = "mods/commandkeys.pw.toml"
hash = "d6032aa4605e55ae33f2dad987b792d8de34b296b7561ca054aa2cb701c23d0b"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "a4057e630b5e100bbf8752e78656bb7a261101f355e0ac12383af7978cc40f40"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "4a77c4c057c6344ab1479c87dd9405007d96a416c04701c493eb6f9d602dff93"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "e918132ab17f31eacc1a055d54bba6ee59a208a5f43af7a89730b39698968ec7"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "71057ffacb79edc48ef50b33ba506255e3da4ad48e8d0eaa4635368097567ba9"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "344ca02ae26f79bc11dc6d65751503613964da6761fcda5a33291dc7d8aae36f"
metafile = true

[[files]]
file = "mods/frozenlib.pw.toml"
hash = "bdf6fa532b9526f8f0592c3a1bf53b76e31221e832b7dac827d4c7d89b5c8285"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "61eb4c52a94a2716fba0a47109eff44951aa70fa3f618cc64a072e8561c59105"
metafile = true

[[files]]
file = "mods/hypixelautogg.pw.toml"
hash = "d3b089f13d6018ddf3af0be6ddf238279a64270e94bf46deeafe44fd0db13792"
metafile = true

[[files]]
file = "mods/in-game-account-switcher.pw.toml"
hash = "b3129bfd9b9bb373f96b7e08ca1981f8e2f69fdadf9d3ff1118c97f3f8e93ba1"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "89989b99381b7616a1145920824ba63990142d019fc1cc784c34d4d6c5ff86fa"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "85465e9b6f11189e6a30acb2c830499d9c5f71fe676d88b5890748f52a19eafc"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "3c3fb7b871d3bf383fe2e7115dfa2400d2e73f03d330c922742acf2da6c422f0"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "d3e8051165c4403238d0c53e3070c4de69e42714f33d5e9ee59ff02aef06c0b9"
metafile = true

[[files]]
file = "mods/noxesium.pw.toml"
hash = "f02298e202c5cbe4c771f5e2dd8835db7e020e36935e108a0b3e46637b7b335f"
metafile = true

[[files]]
file = "mods/quickjoin.pw.toml"
hash = "4c8649026b611777b597b804218e0cf8c1f23c1d01a03afdc2edac318dbffbc4"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "fcf33de193e65ff5acee06575b61ddb9a39dbef7b321501c3842b843b9f26c85"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "394b9225fb333c8bb3c57a654f85675850556d9d3d01d1c95cc3e6a6f75d609a"
metafile = true

[[files]]
file = "mods/rsls.pw.toml"
hash = "c3356166d08f306c98ef527b09656face36da3f10c908dbb8879d15f47532562"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "1bd6e16679d23e6691f119e3f7d5c6c3c424b7ec0c64d3b10bd5b88e4c1e0204"
metafile = true

[[files]]
file = "mods/simple-block-overlay.pw.toml"
hash = "70ba3cdfdea9e099786f8d5f0c722592f466c59e696e9848aa6baaac71e415b6"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "ba8fe5a604cfad57b3effb136f559997a60cc0f670952812e17867d9873426f1"
metafile = true

[[files]]
file = "mods/sound-controller.pw.toml"
hash = "6e0f414996a0e52109a89bcd70fa7e2192471bc02b6258fa25c279b69030e0e5"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "1a8c765b8b5b81b375e6fb9019005cf59d79b9f079a17ac1859acdfc2bf3ac6e"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "f2908d9033570d993a21f671304f08edb7696d65260b58e2b55d0c943f9b172c"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "1a53fd9a425b727d9f3b867b77c92755bc0ef387619c6947b8b64d6fc0782c7a"
metafile = true

[[files]]
file = "mods/toggle-toggle-sprint.pw.toml"
hash = "c8f603f98338f7e5e2844d6b5375491d8d0abbf99fe1c0ff952d1530cc44e5c2"
metafile = true

[[files]]
file = "mods/viafabricplus.pw.toml"
hash = "315866d9c3008883dba16b16820cf28c97792e692220baf69cbbe5415dce9713"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "e3208008761017ce98dabe50c37fad65f56ece476d6b678b7d1eb9eab39bc1a1"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "2dbd942770fba4515e2a69bac73f6effb7535a4dd32883b6cbb60dd8d24b1c22"
metafile = true
