name = "OneClient 1.21.10 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "Utility"
id = "utility-1.21.10-fabric"
update-url = "oneclient/generated/utility-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bb854baaf392f1c4f1e38b1a24b4c3117971ac025bff4fd0abcf1ce14ecafae"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
