name = "OneClient 1.21.10 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.10-fabric"
update-url = "oneclient/generated/utility-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4d75db34ba4405f8c10a0871b090c9e855be507d4fec2f4f1bce33a885a7f18"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
