name = "OneClient 1.21.10 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "Utility"
id = "utility-1.21.10-fabric"
update-url = "oneclient/generated/utility-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "958732d7b9f38ad91df9e2c1ac110b5dd1de2c9c653f79e34f3a4fc35a1cef01"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
