name = "OneClient 1.21.10 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "Utility"
id = "utility-1.21.10-fabric"
update-url = "oneclient/generated/utility-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c19b570c6be911cdaefb63d4380f9c035209173d826b1f7ff34855e01c9ddcf1"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
