hash-format = "sha256"

[[files]]
file = "mods/effecttimerplus.pw.toml"
hash = "8476aba217c53cf8dc84279531933117cbf5f6fb742e39326b7966a2e44e9b41"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "71057ffacb79edc48ef50b33ba506255e3da4ad48e8d0eaa4635368097567ba9"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "91ea5cfda5dfc87a5ed23c5db726afd831e26f4cfbf7be0fe07c3d1a495c9ba2"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "94828f99c4d81ae74fdc9daa04a45bb1bdc030d89140f265c323e9f9d03f2d9e"
metafile = true

[[files]]
file = "mods/no-ones-view-model.pw.toml"
hash = "b403f0ebc6dd00ad51ffab1cc31c7eb9151188a165b0a56c30801adfe4c39d1e"
metafile = true

[[files]]
file = "mods/shaketweaks.pw.toml"
hash = "ea60668a8ecd434e8f40b1a25c77f406ec5b2bc8021bb33acd63c7e4f07f8561"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
hash = "29a8eba169cbaa479575f66a05ed864b993df7049133d0463b094313377d6e6d"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "e3208008761017ce98dabe50c37fad65f56ece476d6b678b7d1eb9eab39bc1a1"
metafile = true
