name = "OneClient 1.21.1 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "HUD"
id = "hud-1.21.1-fabric"
update-url = "oneclient/generated/hud-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd0644101320a04f3d47ef3148142c61d0b49302311932f412e66502536c078b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
