name = "OneClient 1.21.1 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "HUD"
id = "hud-1.21.1-fabric"
update-url = "oneclient/generated/hud-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9773f78b9463696b6b426cd3769165d03c3eb8e95723720efedd035d90f7923"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
