name = "OneClient 1.21.8 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "Utility"
id = "utility-1.21.8-fabric"
update-url = "oneclient/generated/utility-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4da21ab1b9efc12f56035cd1f4cb375a035ff3ecef48d88f905e39649167b4b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.8"

[options]
acceptable-game-versions = []
